DROP TABLE IF EXISTS product ;
CREATE TABLE product ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) ,price integer);

INSERT INTO product (id,name,price) VALUES (1,'ipad',1000);
INSERT INTO product (id,name,price) VALUES (2,'iphone',1200);
INSERT INTO product (id,name,price) VALUES (3,'macbook',2000);
INSERT INTO product (id,name,price) VALUES (4,'macbook pro',2500);